#MCMC Exercise 5
#Problem 1
#Jennifer Starling	
#Feb 8, 2017

#Housekeeping
rm(list=ls())

#--------------------------------------------------------------
# The Markov sequence given by X_{n+1} = rho*X_n + sqrt(1-rho^2)*Z_n
# where (Z_n) are iid N(0,1) random variables, as f ~ N(0,1)
# as the stationary density.  

#Confirm via simulation that the variance of sqrt(N)*Ihat_N = N^(-1/2) sum_{i=1}^{n}X_i
# is sigma^2 = (1 + rho) / (1 - rho).

#Try it for a few rho values.
#--------------------------------------------------------------

std_normal_markov_chain = function(n,rho){
	#FUNCTION:
	#PURPOSE: Calculates the Markov sequence given by X_{n+1} = rho*X_n + sqrt(1-rho^2)*Z_n
	# 			where (Z_n) are iid N(0,1) random variables, as f ~ N(0,1)
	# 			as the stationary density. 
	#
	#INPUTS:	rho = rho values to use for correlation of x's.
	#			n = length of markov chain.
	#OUTPUTS:	fx = sample generated by markov chain.
	#			Ihat_N = 1/N * sum(X_i)
	#			n = sample size input by user.
	
	#Set up required values/vectors.
	z = rnorm(n,0,1)	#Set up n iid N(0,1) draws for (z_n).
	x = rep(0,n+1)		#Set empty vector to hold x values.
	x[1] = rnorm(1,0,1)	#Set x_1 as coming from f ~ N(0,1).  (Not required.)	

	#Iterate through chain to calculate next X_{n+1}
	for (i in 2:n){
		x[i] = rho*x[i-1] + sqrt(1-rho^2) * z[i-1]
	}
	
	#Estimate Ihat_N.
	Ihat_N = (1/n) * sum(x)
	
	#Return function output.
	return(list(fx=x,Ihat_N=Ihat_N,n=n))
}
#--------------------------------------------------------------

#Run markov chain B=10000 times to estimate variance of sqrt(N)*Ihat_N.
n = 1000
rho = .9
B=10000

Ihat_N_seq = rep(0,B)

for (b in 1:B){
	Ihat_N_seq[b] = std_normal_markov_chain(n,rho)$Ihat_N
}

sqrt_N_Ihat_N = sqrt(n) * Ihat_N_seq	#sqrt(N) * Ihat_N

sigma2 = (1+rho) / (1-rho)
sigma2_hat = var(sqrt_N_Ihat_N)

#Display results.
sigma2		#True variance.
sigma2_hat	#Simulated variance.

#--------------------------------------------------------------





